"use strict";
const fs=require("fs"),assert=require("assert");
const read=f=>fs.readFileSync(f,"utf8");
const index=read("index.html"), rewards=read("src/mission_rewards.js"), ui=read("src/mission_ui.js"), deployment=read("src/deployment.js"), deck=read("src/deck.js"), tactics=read("src/tactics.js"), turns=read("src/turns.js"), controller=read("src/controller.js"), events=read("src/events.js"), precheck=read("src/precheck.js");
let n=0;const ok=(v,m)=>{assert.ok(v,m);n++};
ok(index.includes('src/mission_rewards.js'),"modulo reward caricato");
ok(index.indexOf('src/deployment.js')<index.indexOf('src/mission_rewards.js'),"reward dopo deployment");
ok(index.indexOf('src/mission_rewards.js')<index.indexOf('src/render.js'),"reward prima del render");
for(const kind of ["card_cost_sequence","gain_energy_per_controlled_ps","draw_with_discount","draw_cards","gain_energy","enemy_loses_energy_fraction","enemy_discards_hand_fraction"]) ok(rewards.includes(`case "${kind}"`),`handler ${kind}`);
ok(rewards.includes('runtime.missionClass !== "ordinary"'),"guardia ordinaria conservata");
ok(rewards.includes('Math.floor(eligible.length'),"scarto metà floor");
ok(rewards.includes('discardableHandCards'),"protette escluse");
ok(rewards.includes('selectedUids'),"scelta avversario strutturata");
ok(ui.includes('missionUiRequestPlay'),"conferma gioco UI");
ok(ui.includes('missionUiPendingRewardChoiceHtml'),"selettore scarto UI");
ok(ui.includes('missionCanPlayDesperate'),"UI disperate collegata senza regressione ordinarie");
ok(deployment.includes('missionEffectiveCardCost(side, card, normalCost)'),"costo unità collegato");
ok(deployment.includes('missionConsumeCardCostSequence(side, starterCard)'),"starter consuma bonus");
ok(deck.includes('missionConsumeCardCostSequence(side, card)'),"carta mano consuma bonus");
ok(tactics.includes('normalized.cost = missionEffectiveCardCost'),"tattiche ufficiali collegate");
ok(tactics.includes('custom.cost = missionEffectiveCardCost'),"tattiche custom collegate");
ok(turns.includes('Completa la scelta della ricompensa Missione'),"fine turno bloccata");
ok(controller.includes('missionInteractionBlocked'),"mappa bloccata durante scelta");
ok(events.includes('MISSION_PLAYED'),"evento missione giocata");
ok(events.includes('MISSION_REWARD_RESOLVED'),"evento reward risolta");
ok(events.includes('CARD_DISCARDED'),"evento scarto carta");
ok(precheck.includes('Missioni ordinarie F9N8'),"precheck F9N8");
console.log(`F9N8 runtime integration smoke: ${n}/${n} OK`);
