"use strict";
const fs=require("fs"),assert=require("assert");const read=f=>fs.readFileSync(f,"utf8");
const index=read("index.html"),config=read("data/cards_base.js"),rewards=read("src/mission_rewards.js"),ui=read("src/mission_ui.js"),turns=read("src/turns.js"),combat=read("src/combat.js"),statuses=read("src/statuses.js"),abilities=read("src/abilities.js"),precheck=read("src/precheck.js"),data=read("data/missions_base.js"),build=read("src/build_info.js");
let n=0;const ok=(v,m)=>{assert.ok(v,m);n++};
ok(build.includes("C2-STABLE-1-F9O7g-APK-M4c") || build.includes("C2-STABLE-1-F9O7e-APK-M4c") || build.includes("C2-STABLE-1-F9O6-APK-M4c") || build.includes("C2-STABLE-1-F9O5b-APK-M4c") || build.includes("C2-STABLE-1-F9O5a-APK-M4c") || build.includes("C2-STABLE-1-F9O4f-APK-M4c") || build.includes("C2-STABLE-1-F9O4f-APK-M4c") || build.includes("C2-STABLE-1-F9O4e-APK-M4c") || build.includes("C2-STABLE-1-F9O4d-APK-M4c") || build.includes("C2-STABLE-1-F9O4c-APK-M4c") || build.includes("C2-STABLE-1-F9O4b-APK-M4c") || build.includes("C2-STABLE-1-F9O4a-APK-M4c") || build.includes("C2-STABLE-1-F9O4-APK-M4c") || build.includes("C2-STABLE-1-F9O2e-APK-M4c") || build.includes("C2-STABLE-1-F9O2d-APK-M4c")||build.includes("C2-STABLE-1-F9O2c-APK-M4c")||build.includes("C2-STABLE-1-F9O2b-APK-M4c")||build.includes("C2-STABLE-1-F9O2-APK-M4c")||build.includes("C2-STABLE-1-F9O1b-APK-M4c")||build.includes("C2-STABLE-1-F9O1a-APK-M4c")||build.includes("C2-STABLE-1-F9N10-APK-M4c"),"build successiva conserva F9N9");ok(config.includes("desperateMissionsPlayableF9N9: true"),"flag disperate attivo");ok(index.includes("src/card_motion.js") || index.includes("C2-STABLE-1-F9O2e-APK-M4c") || index.includes("C2-STABLE-1-F9O2d-APK-M4c")||index.includes("C2-STABLE-1-F9O2c-APK-M4c")||index.includes("C2-STABLE-1-F9O2b-APK-M4c") || index.includes("C2-STABLE-1-F9O2-APK-M4c")||index.includes("C2-STABLE-1-F9O1b-APK-M4c")||index.includes("C2-STABLE-1-F9O1a-APK-M4c")||index.includes("C2-STABLE-1-F9N10-APK-M4c"),"index build successiva");
for(const kind of ["energy_and_draw_per_condition","distinct_units_per_condition","repeat_attacks_current_round","phase_shield_per_condition","stun_enemy_per_condition"])ok(rewards.includes(`case "${kind}"`),`handler ${kind}`);
ok(rewards.includes("missionCanPlayDesperate"),"validazione disperate");ok(rewards.includes("missionDesperateMultiplier"),"moltiplicatore x1-x3");ok(rewards.includes("mission_target_selection"),"selezione bersagli");ok(rewards.includes("wasted"),"quote sprecate");ok(rewards.includes("repeat_attack_confirmation"),"ripetizione attacco scelta");ok(rewards.includes("missionCleanupEndOfRound"),"cleanup round");ok(ui.includes("missionRewardConfirmTargetSelection"),"UI bersagli");ok(ui.includes("missionRewardConfirmRepeatAttack"),"UI ripetizione");ok(ui.includes("Missioni su cicli multipli"),"UI F9N10 conserva Missioni F9N9");ok(turns.includes("missionCleanupEndOfRound"),"cleanup agganciato");ok(turns.includes("missionMaybeReactivateAfterAction"),"doppia azione agganciata");ok(combat.includes("missionMaybeOfferRepeatAttack"),"attacco ripetuto agganciato");ok(statuses.includes("mission_phase_shield"),"status scudo round");ok(abilities.includes('hasStatus(target, "mission_phase_shield")'),"scudo blocca targeting");ok(precheck.includes("Missioni disperate F9N9"),"precheck F9N9");
for(const id of ["NXMSND01","EXMSND01","LBMSND01","AGMSND01","FBMSND01"])ok(data.includes(`id:"${id}"`),`${id} presente`);
console.log(`F9N9 runtime integration smoke: ${n}/${n} OK`);
