"use strict";
const fs=require("fs"),path=require("path"),assert=require("assert");
const root=path.resolve(__dirname,"..");
const render=fs.readFileSync(path.join(root,"src/render.js"),"utf8");
const build=fs.readFileSync(path.join(root,"src/build_info.js"),"utf8");
const config=fs.readFileSync(path.join(root,"data/cards_base.js"),"utf8");
const precheck=fs.readFileSync(path.join(root,"src/precheck.js"),"utf8");
const css=fs.readFileSync(path.join(root,"css/style.css"),"utf8");
let checks=0;
function ok(value,message){assert.ok(value,message);checks++;}
const boardStart=render.indexOf("function renderBoard()");
const boardEnd=render.indexOf("function renderPanels()",boardStart);
const boardSegment=render.slice(boardStart,boardEnd);
ok(render.includes("const BOARD_DOM_CACHE"),"cache DOM board presente");
ok(render.includes("boardRenderEnsureSkeleton"),"skeleton persistente presente");
ok(render.includes("boardRenderHandleDelegatedClick"),"event delegation presente");
ok(render.includes("boardRenderTargetSets"),"target cache presente");
ok(render.includes("BOARD_DOM_CACHE.unitNodes"),"cache token UID presente");
ok(render.includes("boardRenderTokenSignature"),"firma visuale token presente");
ok(render.includes("boardRenderDiagnostics"),"diagnostica renderer presente");
ok(render.includes('board.dataset.renderer = "incremental-f9o4c"') || render.includes('board.dataset.renderer = "incremental-f9o4b"'),"marker renderer incrementale presente");
ok(!boardSegment.includes('board.innerHTML = ""'),"renderBoard non distrugge il board");
ok(!boardSegment.includes('addEventListener("click"'),"renderBoard non registra listener per cella");
ok(render.includes('board.addEventListener("click", BOARD_DOM_CACHE.delegatedClick)'),"unico listener delegato sul board");
ok(render.includes("entry.element.insertBefore(token, entry.coordLabel)"),"token spostato riusando il nodo");
ok(build.includes("C2-STABLE-1-F9O7g-APK-M4c") || build.includes("C2-STABLE-1-F9O7e-APK-M4c") || build.includes("C2-STABLE-1-F9O6-APK-M4c") || build.includes("C2-STABLE-1-F9O5b-APK-M4c") || build.includes("C2-STABLE-1-F9O5a-APK-M4c") || build.includes("C2-STABLE-1-F9O5-APK-M4c") || build.includes("C2-STABLE-1-F9O4f-APK-M4c") || build.includes("C2-STABLE-1-F9O4f-APK-M4c") || build.includes("C2-STABLE-1-F9O4e-APK-M4c") || build.includes("C2-STABLE-1-F9O4d-APK-M4c") || build.includes("C2-STABLE-1-F9O4c-APK-M4c") || build.includes("C2-STABLE-1-F9O4b-APK-M4c"),"metadata F9O4b");
ok(build.includes("Lezione 5 Fabeot") || build.includes("Lezione 4 Liberti") || build.includes("Lezione 3 Agathoi") || build.includes("Comandi Mano ridotta sotto le abilità di fazione") || build.includes("Tutorial UI State & Resume Hotfix") || build.includes("Lezione 1 Exordium") || build.includes("Tutorial Runtime Foundation") || build.includes("HQ Empty Objective Visual Hotfix") || build.includes("Token Motion & SFX Evaluation") || build.includes("Miniature Taxonomy & Asset Completion") || build.includes("Real Art Thumbnail Cache Finalization Hotfix") || build.includes("Public Bot Card Thumbnail Stability Hotfix") || build.includes("Cross-platform Render Signature Integrity Hotfix") || build.includes("Android Render Stability Hotfix") || build.includes("Incremental DOM Renderer"),"nome build F9O4b/F9O4c o successiva");
ok(config.includes("incrementalBoardDomF9O4b: true"),"flag renderer incrementale");
ok(config.includes("persistentHexNodesF9O4b: true"),"flag celle persistenti");
ok(config.includes("delegatedBoardInputF9O4b: true"),"flag input delegato");
ok(config.includes("cachedBoardTargetsF9O4b: true"),"flag target cache");
ok(config.includes("reusableUnitTokensF9O4b: true"),"flag token riutilizzabili");
ok(precheck.includes("contratto renderer DOM incrementale"),"precheck F9O4b");
ok(css.includes('#board[data-renderer="incremental-f9o4c"]') && css.includes("contain: none"),"F9O4c disattiva containment instabile");
console.log(`F9O4b incremental DOM renderer smoke: ${checks}/${checks} OK`);
