"use strict";
const fs=require("fs"),path=require("path"),vm=require("vm"),assert=require("assert");
const ROOT=path.resolve(__dirname,".."); let checks=0;
const ok=(v,m)=>{assert.ok(v,m);checks++}; const equal=(a,e,m)=>{assert.strictEqual(a,e,m);checks++};
const same=(a,b)=>Array.isArray(a)&&Array.isArray(b)&&a.join(",")===b.join(",");
const distance=(a,b)=>Math.max(Math.abs(a[0]-b[0]),Math.abs(a[1]-b[1]),Math.abs(a[2]-b[2]));
const state={aiMode:"expert",modes:{1:"bot",2:"bot"},turn:5,currentPlayer:1,factions:{1:"Exordium",2:"Nexus"},playerIds:[1,2],energy:{1:5,2:5},pressure:{1:0,2:0},mapId:"relay-test",mapDefinition:{id:"relay-test",name:"Relay Test",movementMultiplier:2},cells:[
 {coord:[-4,4,0],ps:false,control:null},{coord:[0,0,0],ps:true,control:1},{coord:[3,-3,0],ps:true,control:2},{coord:[4,-4,0],ps:false,control:null},{coord:[-1,0,1],ps:false,control:null},{coord:[-1,-1,2],ps:false,control:null},{coord:[1,-1,0],ps:false,control:null}],
 units:[{uid:"hq-ex",side:1,faction:"Exordium",type:"QG",pos:[-4,4,0],alive:true},{uid:"hq-nx",side:2,faction:"Nexus",type:"QG",pos:[4,-4,0],alive:true},
 {uid:"builder",name:"Apotecario Exordium",side:1,faction:"Exordium",type:"Fanteria",weight:"Leggera",cost:1,att:1,pos:[-1,0,1],alive:true,acted:false},
 {uid:"guard",name:"Veicolo Ricognitore",side:1,faction:"Exordium",type:"Veicolo",weight:"Leggero",cost:1,att:2,pos:[0,0,0],alive:true,acted:false},
 {uid:"enemy",side:2,faction:"Nexus",type:"Fanteria",pos:[3,-3,0],alive:true,acted:false}],
 hand:{1:[{cardUid:"card-bastion",sourceType:"unit",blueprintId:"EX4B02",name:"Bastione Armato"}],2:[]},starterCards:{1:{},2:{}}};
const BLUEPRINTS=[{id:"EX4B02",faction:"Exordium",name:"Bastione Armato",type:"Struttura",weight:"Leggera",cost:2,hp:3,att:0,def:2}];
const names=["AI_EXPERT_TURN_STARTED","AI_EXPERT_CONTEXT_CREATED","AI_EXPERT_MODULE_ROUTED","AI_MICROPLAN_SELECTED","AI_MICROPLAN_STEP","AI_MICROPLAN_COMPLETED","AI_MICROPLAN_ABORTED","AI_EXPERT_DECISION","AI_EXPERT_FALLBACK","AI_EXPERT_BUDGET_EXHAUSTED","AI_EXPERT_TURN_COMPLETED"];
const EventTypes=Object.fromEntries(names.map(x=>[x,x])),emitted=[]; let now=10;
const context=vm.createContext({console,Map,Object,Array,Number,String,Boolean,Math,JSON,Date,state,BLUEPRINTS,EventTypes,performance:{now:()=>now+=.1,memory:{usedJSHeapSize:4096}},emitGameEvent:e=>{emitted.push(JSON.parse(JSON.stringify(e)));return e},telemetryRecordExpertDecisionF9T1:()=>{},getEnemyPlayers:p=>[1,2].filter(s=>s!==p),getHq:s=>state.units.find(u=>u.type==="QG"&&u.side===s),combatUnits:s=>state.units.filter(u=>u.alive!==false&&u.side===s&&u.type!=="QG"),countControlledPS:s=>state.cells.filter(c=>c.ps&&c.control===s).length,getUnitAt:c=>state.units.find(u=>u.alive!==false&&same(u.pos,c))||null,getCellAt:c=>state.cells.find(x=>same(x.coord,c))||null,sameCoord:same,hexDistance:distance,movementRangeFor:u=>u.type==="Veicolo"?4:2,getMapMovementMultiplier:()=>2,canAct:u=>u&&!u.acted,canBuildStructures:u=>u&&u.type==="Fanteria",isCellEnterable:()=>true,getMapTerrainAt:()=>null,buildableCells:u=>u&&u.uid==="builder"&&!state.units.some(x=>x.alive!==false&&same(x.pos,[0,0,0]))?[[0,0,0]]:[],movableCells:u=>u&&u.uid==="guard"?[[1,-1,0]]:[],botMoveUnitF9T0:(u,c)=>{u.pos=c.slice()},finishBotMove:u=>{u.acted=true},enemiesNear:()=>[],purchaseLimitReached:()=>false,playerEnergyLocked:()=>false,handCardBlocked:()=>false,effectiveHandUnitCardCost:()=>2,effectiveBlueprintCost:()=>2,starterRoleForBlueprint:()=>"starter_structure",tacticalStarterCapState:()=>({blocked:false}),botPressureProfileF9T0:()=>({totalPs:2,requiredPs:1,pressureWin:5,startRound:20,maxRound:30})});
for(const rel of ["src/expert_ai/expert_common_strategy.js","src/expert_ai/expert_nexus.js","src/expert_ai/expert_exordium.js","src/expert_ai/expert_liberti.js","src/expert_ai/expert_agathoi.js","src/expert_ai/expert_fabeot.js","src/expert_ai/expert_router.js","src/expert_ai/expert_runtime.js"])vm.runInContext(fs.readFileSync(path.join(ROOT,rel),"utf8"),context,{filename:rel});
const session=vm.runInContext("expertBeginTurnF9T1(1)",context);
equal(session.module.moduleId,"expert-exordium-f9t2d3","router F9T2c"); equal(session.module.invokedModules,1,"un solo modulo"); ok(session.plan,"piano selezionato con PS occupato");
equal(session.plan.orderedSteps[0].action,"advance_unit_pre_purchase","movimento prima"); equal(session.plan.orderedSteps[1].action,"build_roster","costruzione dopo"); equal(session.plan.primaryActorId,"guard","occupante PS è la guardia"); equal(session.plan.reservedEnergy,2,"riserva ENE");
ok(emitted.some(e=>e.type==="AI_EXPERT_DECISION"&&e.data&&e.data.decision&&e.data.decision.kind==="bastion_relay_candidate_audit_batch"&&Array.isArray(e.data.decision.audits)&&e.data.decision.audits.some(a=>a.candidateValid===true)),"audit candidato valido");
equal(vm.runInContext("expertCanSpendEnergyF9T2(1,4)",context),false,"riserva blocca spesa");
equal(vm.runInContext("expertFactionTryPrePurchasePlanStepF9T2a(1)",context),true,"guardia liberata pre-acquisto"); equal(session.plan.currentStep,1,"step movimento completato"); ok(!same(state.units.find(u=>u.uid==="guard").pos,[0,0,0]),"PS libero"); equal(session.plan.reservedEnergy,2,"riserva ancora attiva");
const choice=vm.runInContext("expertFactionRosterChoiceF9T2(1)",context); ok(choice&&choice.bp.id==="EX4B02","Bastione scelto"); equal(choice.builder.uid,"builder","builder dichiarato"); ok(same(choice.coord,[0,0,0]),"target PS");
state.energy[1]-=2; state.units.push({uid:"bastion",side:1,faction:"Exordium",type:"Struttura",id:"EX4B02",pos:[0,0,0],alive:true,acted:true});
equal(vm.runInContext("expertFactionObserveRosterPlayF9T2(1,"+JSON.stringify({bp:BLUEPRINTS[0],coord:[0,0,0],cost:2})+")",context),true,"costruzione osservata"); equal(session.plan.status,"completed","piano completato"); equal(session.plan.currentStep,2,"due step"); equal(session.plan.reservedEnergy,0,"riserva liberata");
const summary=vm.runInContext("expertCompleteTurnF9T1(1,{guardIterations:1})",context); equal(summary.planStatus,"completed","riepilogo"); equal(summary.fallbackUsed,false,"no fallback"); equal(summary.candidateCount,1,"un candidato"); ok(summary.candidateAuditCount>=2,"audit PS registrati"); equal(vm.runInContext("Object.keys(expertRuntimeStateF9T1.activeByPlayer).length",context),0,"runtime pulito");
console.log(`F9T2b Exordium Bastion Relay regression smoke: ${checks}/${checks} verifiche superate`);
