"use strict";

const fs = require("fs");
const path = require("path");
const runtimeManifest = require("./runtime_profile_manifest");

const COPY_ENTRIES = Object.freeze(["index.html", "assets", "css", "data", "locales", "src", "LICENSE", "Asset_License"]);
const PUBLIC_RELEASE_FILES = Object.freeze([
  "docs/release/STARTER_1_0_RULEBOOK_IT.md",
  "docs/release/STARTER_1_0_RULEBOOK_EN.md",
  "docs/release/STARTER_1_0_PLAYER_GUIDE_IT_EN.md",
  "docs/release/STARTER_1_0_GLOSSARY_IT_EN.md",
  "docs/release/STARTER_1_0_STATISTICS_REGISTER.md",
  "docs/release/STARTER_1_0_CHANGELOG.md",
  "docs/release/STARTER_1_0_WEBSITE_CANONICAL_COPY.md",
  "docs/release/STARTER_1_0_CREDITS_LICENSES.md"
]);
const DISTRIBUTION_EXCLUDE_FILES = Object.freeze([
  "data/ar_ac1_acceptance_manifest.json",
  "data/official_decks_f9s1c1_audit.json",
  "data/s2_c7_regression_matrix.json"
]);

function stageRuntime({ rootDir, outputDir, profile }) {
  const root = path.resolve(rootDir);
  const output = path.resolve(outputDir);
  if (!['dev', 'distribution'].includes(profile)) throw new Error(`Invalid profile: ${profile}`);
  const relativeOutput = path.relative(root, output);
  if (!relativeOutput || relativeOutput.startsWith("..") || path.isAbsolute(relativeOutput)) {
    throw new Error("Output must be a dedicated directory inside the repository root");
  }
  fs.rmSync(output, { recursive: true, force: true });
  fs.mkdirSync(output, { recursive: true });
  for (const entry of COPY_ENTRIES) {
    fs.cpSync(path.join(root, entry), path.join(output, entry), { recursive: true });
  }
  for (const relativePath of PUBLIC_RELEASE_FILES) {
    const destination = path.join(output, relativePath);
    fs.mkdirSync(path.dirname(destination), { recursive: true });
    fs.copyFileSync(path.join(root, relativePath), destination);
  }
  fs.writeFileSync(
    path.join(output, "data", "runtime_profile_build.js"),
    `"use strict";\n\n// Generated by tools/stage_runtime.js.\nglobalThis.ARENA_RUNTIME_BUILD_PROFILE = "${profile}";\n`,
    "utf8"
  );
  if (profile === "distribution") {
    for (const modulePath of runtimeManifest.devOnly) fs.rmSync(path.join(output, modulePath), { force: true });
    for (const relativePath of DISTRIBUTION_EXCLUDE_FILES) fs.rmSync(path.join(output, relativePath), { force: true });
    const assetInventory = JSON.parse(fs.readFileSync(path.join(root, "data", "required_assets.json"), "utf8"));
    for (const group of ["devOnly", "legacy", "unused"]) {
      for (const item of assetInventory[group] || []) fs.rmSync(path.join(output, ...item.path.split("/")), { force:true });
    }
  }
  return { profile, output, copied: COPY_ENTRIES.length + PUBLIC_RELEASE_FILES.length, excluded: profile === "distribution" ? runtimeManifest.devOnly.length : 0 };
}

if (require.main === module) {
  const profileIndex = process.argv.indexOf("--profile");
  const outputIndex = process.argv.indexOf("--output");
  const profile = profileIndex >= 0 ? process.argv[profileIndex + 1] : "distribution";
  const outputArg = outputIndex >= 0 ? process.argv[outputIndex + 1] : `_site_${profile}`;
  const result = stageRuntime({ rootDir: path.resolve(__dirname, ".."), outputDir: path.resolve(outputArg), profile });
  console.log(`AR-AC1 ${result.profile} runtime staged: ${result.output} (${result.excluded} DEV modules excluded)`);
}

module.exports = { COPY_ENTRIES, PUBLIC_RELEASE_FILES, DISTRIBUTION_EXCLUDE_FILES, stageRuntime };
